### ISSUE TITLE
help dataset

### ISSUE THREAD

**Issue by Yang-Yonghong** [varunsingh3000/Driver-Drowsiness-Detection#1]
I am pleased to see your replication of the RTA-RLDD paper. I am a current student and am in need of the RTA-RLDD dataset for experiments related to fatigue detection. The official dataset download link http://vlm1.uta.edu/~athitsos/projects/drowsiness/ is currently unavailable. I would appreciate it if you could provide me with access to the RTA-RLDD dataset. Thank you very much.

**Comment by varunsingh3000** [comment]
Hi @Yang-Yonghong, I am not currently in possession of the dataset since I have stopped working on this project. You are right, the official link seems to not be working. I think your best bet would be to email the contact mentioned at the end of their RLDD dataset homepage https://sites.google.com/view/utarldd/home and hopefully they can provide you with the dataset. Good Luck!
